apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +optional Incoming connection details for the component (AKA endpoints).
  inbound:
    - name: backend
      port: 3000
      type: REST
      networkVisibility: Organization
      context: /
      schemaFilePath: openapi.yaml
