apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: bff
      port: 5172
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///saumohackathon/backend/plvhsm/197f7/v1/ORGANIZATION
      connectionConfig: 01ef0719-60b7-1a68-a468-7645b1c36f65
      env:
      - from: ServiceURL
        to: BACKEND_SERVICE_URL
      - from: ConsumerKey
        to: BACKEND_OAUTH_CLIENT_ID
      - from: ConsumerSecret
        to: BACKEND_OAUTH_CLIENT_SECRET
      - from: TokenURL
        to: BACKEND_OAUTH_TOKEN_URL