apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: bff
      port: 5172
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///codechallenge/appointment-management/cmrqnc/8b1c3/v1.0/ORGANIZATION
      connectionConfig: 01eef67c-b6e6-17c0-9120-68782ddbb0c9
      env:
      - from: ServiceURL
        to: BACKEND_SERVICE_URL
      - from: ConsumerKey
        to: BACKEND_OAUTH_CLIENT_ID
      - from: ConsumerSecret
        to: BACKEND_OAUTH_CLIENT_SECRET
      - from: TokenURL
        to: BACKEND_OAUTH_TOKEN_URL